
import React from 'react';


export const metadata = {
  title: "Create Next App",
  description: "Generated by  create next app",
};

const Layout = ({children}) => {
    return (
        <div>
            
            {children}
        </div>
    );
};

export default Layout;