import Navbar from '@/components/navbar/Navbar';
import React from 'react';


export const metaData = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({children}) => {
    return (
        <div>
            <Navbar></Navbar>
            {children}
        </div>
    );
};

export default Layout;